apiVersion: com.accantosystems.stratoss/v1alpha1
kind: ALM
metadata:
  name: awesome
spec:
  secure: true
  springCloudConfigLabel: master
  springProfilesActive: ""
  deploymentType: Middle
  dockerRepo: nexus.accanto.com:5000
  release: http://10.220.217.248:8086/accanto/lm-operator-releases/raw/master/2.1.0-alpha-2633.yaml
  configurator:
    Run: true
  conductor:
    JVMOptions: -Xmx256m
  brent:
    JVMOptions: -Xmx256m
  apollo:
    JVMOptions: -Xmx256m
  galileo:
    JVMOptions: -Xmx1024m
  talledega:
    JVMOptions: -Xmx1024m
  daytona:
    JVMOptions: -Xmx1024m
  nimrod:
    JVMOptions: -Xmx256m
  ishtar:
    JVMOptions: -Xmx256m
  relay:
    JVMOptions: -Xmx256m
  watchtower:
    JVMOptions: -Xmx1024m
  doki:
    JVMOptions: -Xmx512m