apiVersion: apps/v1
kind: Deployment
metadata:
  name: lm-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: lm-operator
  template:
    metadata:
      labels:
        name: lm-operator
    spec:
      serviceAccountName: lm-operator
      containers:
        - name: lm-operator
          image: accanto/lm-operator:0.1.0
          command:
          - lm-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "lm-operator"
